import type { TenantConfig } from "./tenant";
import { routing } from "@/i18n/routing";

export type Category = "ueberpruefung" | "vertiefung" | "treffen" | "fortgeschritten";
export type Tab = "im-center" | Category;

export type MeditatorsUrls = Pick<
  TenantConfig,
  | "meditators_ueberpruefung_url"
  | "meditators_vertiefung_url"
  | "meditators_treffen_url"
  | "meditators_fortgeschrittenentechniken_url"
>;

// Vertiefung and Fortgeschritten always have a national default URL → always link out.
// Überprüfung and Treffen have no national default → internal unless a tenant overrides.
const DEFAULT_VERTIEFUNG_URL = "https://tm-wochenende.de/tm-kraft-der-stille/";
const DEFAULT_FORTGESCHRITTEN_URL = "https://tm-wochenende.de/fortgeschritten/";

export function getExternalUrl(urls: MeditatorsUrls, id: Category): string | null {
  switch (id) {
    case "ueberpruefung": return urls.meditators_ueberpruefung_url;
    case "vertiefung": return urls.meditators_vertiefung_url ?? DEFAULT_VERTIEFUNG_URL;
    case "treffen": return urls.meditators_treffen_url;
    case "fortgeschritten": return urls.meditators_fortgeschrittenentechniken_url ?? DEFAULT_FORTGESCHRITTEN_URL;
  }
}

const SLUG_BY_CATEGORY: Record<Category, string> = {
  ueberpruefung: "checking",
  vertiefung: "wochenende",
  treffen: "treffen",
  fortgeschritten: "fortgeschritten",
};

const CATEGORY_BY_SLUG: Record<string, Category> = Object.fromEntries(
  Object.entries(SLUG_BY_CATEGORY).map(([category, slug]) => [slug, category as Category]),
);

export function slugForTab(tab: Tab): string | null {
  return tab === "im-center" ? null : SLUG_BY_CATEGORY[tab];
}

export function pathForTab(locale: string, tab: Tab): string {
  const base = locale === routing.defaultLocale ? "/events" : `/${locale}/events`;
  const slug = slugForTab(tab);
  return slug ? `${base}/${slug}` : base;
}

// Open Graph link-preview descriptor per tab. titleKey/blurbKey are Events-namespace
// message keys; the OG title is `t(titleKey) – {city}`. Images are 1200×630 JPG crops
// generated by scripts/generate-og-images.mjs.
export const OG_BY_TAB: Record<Tab, { titleKey: string; blurbKey: string; image: string }> = {
  "im-center": { titleKey: "ogEventsTitle", blurbKey: "ogEventsBlurb", image: "/og/events.jpg" },
  ueberpruefung: { titleKey: "catUeberpruefung", blurbKey: "ogUeberpruefungBlurb", image: "/og/checking.jpg" },
  vertiefung: { titleKey: "catVertiefung", blurbKey: "ogVertiefungBlurb", image: "/og/wochenende.jpg" },
  treffen: { titleKey: "catTreffen", blurbKey: "ogTreffenBlurb", image: "/og/treffen.jpg" },
  fortgeschritten: { titleKey: "catFortgeschritten", blurbKey: "ogFortgeschrittenBlurb", image: "/og/fortgeschritten.jpg" },
};

export function resolveInitialTab(
  slug: string | undefined,
  urls: MeditatorsUrls,
): Tab {
  if (!slug) return "im-center";
  const category = CATEGORY_BY_SLUG[slug];
  if (category && !getExternalUrl(urls, category)) return category;
  return "im-center";
}
